name: Build and Push Docker Image to AWS ECR
on:
  push:
    branches: [ main ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Amazon ECR
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      run: |
        aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin $ECR_REGISTRY

    - name: Build and push Docker image
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      run: |
        IMAGE_TAG=$(date +%Y%m%d%H%M%S)
        docker build -t $ECR_REGISTRY/my-repo:$IMAGE_TAG .
        docker push $ECR_REGISTRY/my-repo:$IMAGE_TAG
